import type { AgentModel } from "./types";

const envModels = (process.env.NEXT_PUBLIC_AI_MODEL_NAME || process.env.NEXT_PUBLIC_OLLAMA_MODELS || "gpt-4o-mini").split(",").map(m => m.trim());

const ACCENTS = ["#e07b53", "#10a37f", "#38bdf8", "#a78bfa", "#fbbf24"];

export const AGENT_MODELS: AgentModel[] = envModels.map((modelId, index) => ({
  id: modelId,
  name: modelId,
  vendor: "Ollama Local",
  tagline: "Custom model dari .env",
  price: "Free",
  speed: 80,
  quality: 85,
  accent: ACCENTS[index % ACCENTS.length],
}));

export const SAMPLE_IDEAS = [
  "Marketplace jual beli preloved sneakers dengan escrow dan verifikasi keaslian oleh tim curator",
  "Aplikasi booking klinik gigi dengan antrian real-time dan reminder via WhatsApp",
  "Platform belajar coding interaktif untuk anak SMP dengan gamifikasi XP dan leaderboard",
  "Aplikasi catatan keuangan pribadi yang otomatis kategorisasi transaksi pakai AI",
  "Social platform untuk komunitas pehobi kopi: forum, jual biji kopi, dan kelas cupping",
  "SaaS manajemen inventori untuk UMKM kuliner dengan scanning barcode dan stok real-time",
  "Website top up game (Mobile Legends, Free Fire, Genshin Impact) dengan QRIS, e-wallet, dan riwayat transaksi",
  "Aplikasi kasir untuk toko retail: scan barcode, struk termal, shift kas, dan laporan penjualan",
  "CRM penjualan untuk tim sales: pipeline deal, follow-up otomatis, dan forecast",
  "Platform LMS kursus online dengan sertifikat digital dan kelas live",
];

export const PROJECT_TYPES = [
  { id: "static", label: "Static / Client-side", emoji: "⚡" },
  { id: "simple", label: "Simple App", emoji: "📝" },
  { id: "topup", label: "Top Up / Game", emoji: "🎮" },
  { id: "pos", label: "POS / Kasir", emoji: "🧾" },
  { id: "crm", label: "CRM / Sales", emoji: "🤝" },
  { id: "lms", label: "LMS / E-Learning", emoji: "🎓" },
  { id: "ecommerce", label: "E-commerce / Marketplace", emoji: "🛒" },
  { id: "saas", label: "SaaS / Web App", emoji: "🧩" },
  { id: "social", label: "Social / Komunitas", emoji: "👥" },
  { id: "booking", label: "Booking / Reservasi", emoji: "📅" },
  { id: "fintech", label: "Fintech / Payment", emoji: "💸" },
  { id: "edtech", label: "EdTech / Learning", emoji: "🎓" },
  { id: "health", label: "Health / Klinik", emoji: "🩺" },
  { id: "ai-tool", label: "AI Tool", emoji: "🤖" },
  { id: "content", label: "Content / Media", emoji: "📰" },
  { id: "logistics", label: "Logistics / Delivery", emoji: "🚚" },
  { id: "other", label: "Lainnya", emoji: "✨" },
];

export const PROJECT_TYPES_MAP = Object.fromEntries(
  PROJECT_TYPES.map((p) => [p.id, p]),
);

export const NAME_SUFFIXES = [
  "Hub",
  "Desk",
  "Flow",
  "Kit",
  "Space",
  "ly",
  "io",
  "X",
  "App",
  "Go",
];

export const PRIORITY_ORDER = ["P0", "P1", "P2"] as const;

export const TECH_LAYERS: { id: string; label: string; desc: string; placeholder: string; options: string[] }[] = [
  {
    id: "frontend",
    label: "Frontend",
    desc: "UI & tampilan user",
    placeholder: "Cari atau ketik frontend...",
    options: [
      "Next.js",
      "React (Vite)",
      "TanStack Start",
      "React Router 7 / Remix",
      "Astro",
      "Vue.js",
      "Nuxt",
      "Svelte",
      "SvelteKit",
      "Solid / SolidStart",
      "Qwik",
      "Angular",
      "HTMX + Server-rendered",
      "Flutter",
      "React Native",
      "Expo (React Native)",
      "SwiftUI (iOS native)",
      "Jetpack Compose (Android native)",
      "Tauri (desktop)",
      "Electron (desktop)",
    ],
  },
  {
    id: "backend",
    label: "Backend",
    desc: "Logic & API server",
    placeholder: "Cari atau ketik backend...",
    options: [
      "Node.js (Express/Fastify)",
      "NestJS",
      "Hono",
      "Elysia (Bun)",
      "Bun runtime",
      "Deno",
      "Python (FastAPI/Django)",
      "Go (Fiber/Echo)",
      "Rust (Axum/Actix)",
      "Laravel (PHP)",
      "Ruby on Rails",
      "Java (Spring Boot)",
      ".NET (ASP.NET Core)",
      "Cloudflare Workers",
      "Edge Functions (Vercel/Netlify)",
      "Convex (BaaS)",
      "InsForge (BaaS)",
      "Supabase (BaaS)",
      "Firebase (BaaS)",
      "Appwrite (BaaS)",
      "Pocketbase (BaaS)",
    ],
  },
  {
    id: "database",
    label: "Database",
    desc: "Penyimpanan data",
    placeholder: "Cari atau ketik database...",
    options: [
      "PostgreSQL",
      "Neon (serverless Postgres)",
      "Supabase (Postgres)",
      "Prisma Postgres",
      "MySQL",
      "PlanetScale (MySQL)",
      "SQLite",
      "Turso (libSQL)",
      "Cloudflare D1",
      "MongoDB",
      "Firebase / Firestore",
      "Convex",
      "Redis / Upstash",
      "DynamoDB",
      "CockroachDB",
      "ClickHouse (analytics)",
      "Xata",
    ],
  },
  {
    id: "deploy",
    label: "Deployment",
    desc: "Hosting & infra",
    placeholder: "Cari atau ketik deployment...",
    options: [
      "Vercel",
      "Netlify",
      "Cloudflare Pages / Workers",
      "Railway",
      "Render",
      "Fly.io",
      "Koyeb",
      "Northflank",
      "Deno Deploy",
      "AWS (Amplify/ECS/Lambda)",
      "Google Cloud (Cloud Run)",
      "Azure (App Service)",
      "Hetzner Cloud",
      "DigitalOcean (App Platform)",
      "VPS (manual)",
      "Coolify (self-host PaaS)",
      "Docker / Kubernetes (self-host)",
    ],
  },
];

export const STACK_BY_TYPE: Record<string, string[]> = {
  static: ["HTML / CSS / JS", "-", "-", "Vercel"],
  simple: ["Next.js 16 / TS", "Supabase (BaaS)", "Supabase (Postgres)", "Vercel"],
  pos: ["Next.js 16 / TS", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "S3 + CloudFront"],
  crm: ["React 19", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "Sentry + OpenTelemetry"],
  lms: ["Next.js 16 / TS", "Django", "PostgreSQL 17", "Redis 7", "S3 + CloudFront"],
  topup: ["React 19", "Laravel 12 / PHP 8.3", "MySQL 8", "Midtrans", "Xendit"],
  ecommerce: ["Next.js 16 / TS", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "Midtrans"],
  saas: ["Next.js 16 / TS", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "Docker"],
  social: ["React 19", "Go", "PostgreSQL 17", "Redis 7", "S3 + CloudFront"],
  booking: ["Next.js 16 / TS", "Laravel 12 / PHP 8.3", "MySQL 8", "Redis 7", "Xendit"],
  fintech: ["React 19", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "Midtrans"],
  edtech: ["Next.js 16 / TS", "Django", "PostgreSQL 17", "Redis 7", "S3 + CloudFront"],
  health: ["React 19", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "S3 + CloudFront"],
  "ai-tool": ["Next.js 16 / TS", "Python FastAPI", "PostgreSQL 17", "pgvector", "Redis 7"],
  content: ["Next.js 16 / TS", "Node 24 / Fastify", "PostgreSQL 17", "S3 + CloudFront", "Redis 7"],
  logistics: ["React 19", "Go", "PostgreSQL 17", "Redis 7", "Docker"],
  other: ["Next.js 16 / TS", "Node 24 / Fastify", "PostgreSQL 17", "Redis 7", "Docker"],
};
